# -*- mode: ruby -*-
# vi: set ft=ruby

ENV["LC_ALL"] = "en_US.UTF-8"

Vagrant.configure("2") do |config|
    config.vm.box = "centos/8"
    config.vm.synced_folder ".", "/vagrant", disabled: true

    config.vm.provider :virtualbox do |v|
        v.memory = 512
        v.linked_clone = true
        v.check_guest_additions = false
        v.customize ["modifyvm", :id, "--cpuexecutioncap", "25"]
    end

    config.vm.define "db01" do |db|
        db.vm.hostname = "db01.local"
        db.vm.network :private_network, ip: "172.22.100.10", virtualbox__intnet: "crontab"
    end

    # config.vm.define "bs01" do |bs|
    #     bs.vm.hostname = "bs01.local"
    #     bs.vm.network :private_network, ip: "172.22.100.20", virtualbox__intnet: "crontab"
    # end
end