# -*- mode: ruby -*-
# vi: set ft=ruby

ENV["LC_ALL"] = "en_US.UTF-8"

Vagrant.configure("2") do |config|
    config.vm.box = "centos/8"
    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vm.provision "shell", path: "scripts/01-bootstrap.sh"

    config.vm.provider :virtualbox do |v|
        v.memory = 512
        v.linked_clone = true
        v.check_guest_additions = false
        v.customize ["modifyvm", :id, "--cpuexecutioncap", "25"]
    end

    config.vm.define "client01" do |client|
        client.vm.hostname = "client01.local"
        client.vm.network :private_network, ip: "172.22.200.20", virtualbox__intnet: "08-troubleshooting"
    end

    config.vm.define "db01" do |client|
        client.vm.hostname = "db01.local"
        client.vm.network :private_network, ip: "172.22.100.30", virtualbox__intnet: "08-troubleshooting"
        client.vm.provision "shell", path: "scripts/03-install-db-service.sh"
    end

    config.vm.define "server01" do |server|
        server.vm.hostname = "server01.local"
        server.vm.network :private_network, ip: "172.22.100.10", virtualbox__intnet: "08-troubleshooting"
        server.vm.network :private_network, ip: "172.22.100.15", virtualbox__intnet: "08-troubleshooting"
        server.vm.provision "file", source: "app", destination: "$HOME/app"
        server.vm.provision "shell", path: "scripts/02-install-nginx-service.sh"
    end
end